# Generated by Django 3.0.3 on 2021-08-09 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import greek.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=100)),
                ('person_clients', models.CharField(blank=True, max_length=100)),
                ('top_chefs', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('city_photo', models.ImageField(null=True, storage=greek.storage.OverwriteStorage(), upload_to='cities')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(null=True, storage=greek.storage.OverwriteStorage(), upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Feeddback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(blank=True, max_length=100)),
                ('customer_second_name', models.CharField(blank=True, max_length=100)),
                ('feedback_description', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(max_length=1000)),
                ('customer_photo', models.ImageField(blank=True, null=True, storage=greek.storage.OverwriteStorage(), upload_to='customer')),
                ('deleted', models.BooleanField()),
                ('show', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeddback_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
