# Generated by Django 3.0.3 on 2021-07-13 19:44

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210713_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=1000, null=True, storage=web.models.OverwriteStorage(), upload_to='images'),
        ),
    ]
