# Generated by Django 3.0.3 on 2021-07-13 19:50

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210713_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=web.models.OverwriteStorage(), upload_to='images'),
        ),
    ]
