# Generated by Django 3.0.3 on 2021-07-13 19:50

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210713_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, storage=web.models.OverwriteStorage(), upload_to='images'),
        ),
    ]
