# Generated by Django 3.0.3 on 2021-07-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
