# Generated by Django 3.0.3 on 2021-07-13 21:39

from django.db import migrations, models
import web.storage


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210714_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, storage=web.storage.OverwriteStorage(), upload_to='images'),
        ),
    ]
