# Generated by Django 3.0.3 on 2021-07-14 10:22

from django.db import migrations, models
import web.storage


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=100)),
                ('city_photo', models.ImageField(null=True, storage=web.storage.OverwriteStorage(), upload_to='cities')),
            ],
        ),
    ]
