# Generated by Django 3.0.3 on 2021-07-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_cities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='Citie',
        ),
    ]
