# Generated by Django 3.0.3 on 2021-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20210714_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_clients', models.CharField(blank=True, max_length=100)),
                ('top_chefs', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
