# Generated by Django 3.0.3 on 2021-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_citydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydetail',
            name='city_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
