# Generated by Django 3.0.3 on 2021-07-15 13:27

from django.db import migrations, models
import web.storage


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_citydetail_city_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citie',
        ),
        migrations.AddField(
            model_name='citydetail',
            name='city_photo',
            field=models.ImageField(null=True, storage=web.storage.OverwriteStorage(), upload_to='cities'),
        ),
    ]
