# Generated by Django 3.0.3 on 2021-07-20 09:24

from django.db import migrations, models
import web.storage


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20210715_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feddback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(blank=True, max_length=100)),
                ('customer_secondname', models.CharField(blank=True, max_length=100)),
                ('feedback', models.TextField(blank=True, max_length=1000)),
                ('customer_photo', models.ImageField(null=True, storage=web.storage.OverwriteStorage(), upload_to='customer')),
            ],
        ),
    ]
