# Generated by Django 3.0.3 on 2021-07-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_feddback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feddback',
            new_name='Feeddback',
        ),
    ]
