# Generated by Django 3.0.3 on 2021-07-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20210720_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeddback',
            old_name='customer_firstname',
            new_name='customer_first_name',
        ),
        migrations.RenameField(
            model_name='feeddback',
            old_name='customer_secondname',
            new_name='customer_second_name',
        ),
    ]
