# Generated by Django 3.0.3 on 2021-07-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20210720_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeddback',
            name='customer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer'),
        ),
    ]
