# Generated by Django 3.0.3 on 2021-07-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20210721_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeddback',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
