# Generated by Django 3.0.3 on 2021-07-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20210725_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeddback',
            old_name='deleted',
            new_name='delete',
        ),
    ]
