# Generated by Django 3.0.3 on 2021-08-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20210728_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeddback',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
