# Generated by Django 3.0.3 on 2021-08-18 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0034_feeddback_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(blank=True, max_length=100)),
                ('customer_second_name', models.CharField(blank=True, max_length=100)),
                ('order_description', models.CharField(blank=True, max_length=100)),
                ('placed', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('order', models.TextField(max_length=1000)),
                ('customer_photo', models.ImageField(blank=True, null=True, storage=web.storage.OverwriteStorage(), upload_to='customer')),
                ('deleted', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
