# Generated by Django 3.0.3 on 2021-08-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, choices=[('France', 'France'), ('Germany', 'Germany'), ('Great Britain', 'Great Britain'), ('Greece', 'Greece')], default='Greece', max_length=20),
        ),
    ]
