# Generated by Django 3.0.3 on 2021-09-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20210818_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOrNot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.BooleanField(default=True)),
            ],
        ),
    ]
